name: rna-class
channels:
  - plotly
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - notebook=6.1.4=py38_0
  - jupyterlab=2.2.6=py_0
  - ipywidgets=7.5.1=py_1
  - ipython=7.19.0=py38hb070fc8_0
  - r-base=3.6.3
  - r-tidyverse=1.2.1
  - r-rcolorbrewer=1.1_2
  - r-ggplot2=3.0.0
  - r-stringr=1.3.1
  - plotly=4.14.3
  - conda-forge::r-msigdbr=7.4.1
  - bioconda::r-venndiagram=1.6.16
  - bioconda::bioconductor-enrichplot=1.0.2
  - bioconda::bioconductor-clusterprofiler=3.8.1
  - bioconda::bioconductor-enhancedvolcano=1.10.0
  - bioconda::bioconductor-pcatools=2.4.0
  - bioconda::r-pheatmap=1.0.8
  - bioconda::bioconductor-deseq=1.26.0
