name: rna-class
channels:
  - plotly
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - notebook
  - jupyterlab
  - ipywidgets
  - ipython
  - r-base
  - r-tidyverse
  - r-rcolorbrewer
  - r-ggplot2
  - r-stringr
  - plotly
  - conda-forge::r-msigdbr
  - bioconda::r-venndiagram
  - bioconda::bioconductor-enrichplot
  - bioconda::bioconductor-clusterprofiler
  - bioconda::bioconductor-enhancedvolcano
  - bioconda::bioconductor-pcatools
  - bioconda::r-pheatmap
  - bioconda::bioconductor-deseq2
